const getters = {
  sidebar: state => state.app.sidebar,
  language: state => state.app.language,
  size: state => state.app.size,
  device: state => state.app.device,
  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,
  token: state => state.user.token,
  avatar: state => state.user.avatar,
  name: state => state.user.name,
  introduction: state => state.user.introduction,
  status: state => state.user.status,
  roles: state => state.user.roles,
  setting: state => state.user.setting,
  permission_routers: state => state.permission.routers,
  addRouters: state => state.permission.addRouters,
  errorLogs: state => state.errorLog.logs,
  code: state => state.global.code,
  jzrq: state => state.global.jzrq,
  lastDaysToAlert: state => state.global.lastDaysToAlert,
  tokenstartToCheck: state => state.global.tokenstartToCheck,
  tokenOverTime: state => state.global.tokenOverTime,
  tokenStartTime: state => state.user.tokenStartTime,
  isRefreshingToken: state => state.user.isRefreshingToken,
  systemName: state => state.global.systemName,
}
export default getters
